# Change these first
owner: cmadera # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: SeeU
    url: https://seeu.me
  - name: Bigbank
    url: https://bigbank.com.br
  - name: Up SeeU
    url: http://up.seeu.me
#  - name: Test for HEAD
#    method: HEAD
#    url: http://up.seeu.me
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  name: Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: git.seeu.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /cmadera/uptime
  #introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for my websites, powered entirely by GitHub
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
